# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.chrisilott.com
title: Chris Ilott
email: chris@chrisilott.com
author: Chris Ilott
description: > # "Chris Ilott: Visual Merchandiser"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/chris_ilott
  - title: linkedin
    url: https://www.linkedin.com/in/chrisilott
