url: http://www.chrisilott.com
baseurl: ""

# Site settings
title: Chris Ilott
email: chris@chrisilott.com
description: "Chris Ilott - Visual Merchandiser"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://au.linkedin.com/in/chrisilott
  - title: twitter
    url: https://twitter.com/chris_ilott
  - title: pinterest
    url: https://www.pinterest.com/chrisilott/
  - title: instagram
    url: https://instagram.com/cilott/

# Postal address (add as many lines as necessary)
address:
  - line: Melbourne
  - line: Australia

# Build settings
markdown: kramdown
permalink: pretty